# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2013

# Custom your favicon.ico in `site/source`
#favicon: https://cdn.dribbble.com/users/91334/screenshots/3508864/orderforge.jpg
favicon: favicon.ico
# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives: /archives
  About: /about
  Rss: /atom.xml

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: true

widget_custom:
    title: It's me
    content: <p>这家伙很懒，什么都没留下</p>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
#  fancybox: false
  fancybox: true

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname: opsforce


# ===========================================
# Version
# ===========================================
version: 1.1
