menu:
  归档: /archives
  阅读: /books
  电影: /movies
  关于: /about
rss: /atom.xml
description:
social:
  weibo: http://weibo.com/izekr
  github: https://github.com/opsforce
#  stack_overflow:
#  facebook:
#  twitter: https://twitter.com/opsforce
#  google_plus: https://plus.google.com/118328736821069549236
  instagram: https://www.instagram.com/opsforce

page_comment: true
#logo: /images/logo.png
logo: https://ws4.sinaimg.cn/large/006tNc79ly1fqd5hpo5g0j3064064mx3.jpg
background:
#  cover: /images/background-cover.jpg
#  cover: https://images.unsplash.com/photo-1516116216624-53e697fedbea?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0f388c03c3f15daa78a7afd93b2ff3e3&auto=format&fit=crop&w=1400&q=80
#  cover: https://images.unsplash.com/photo-1536065998491-91b0ffda8909?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=def50499ac5020f7bb4df6991004c286&auto=format&fit=crop&w=1951&q=80
  cover: https://images.unsplash.com/photo-1537283211-be6e1d3a549b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3a98cccc95076a3f4db6a786d897d746&auto=format&fit=crop&w=1568&q=80
  color: cover-disabled

fancybox: true

cloudtie_productkey: 7e456de65fb945698c448c72191454ce

google_analytics: UA-90629160-1

#favicon: /images/favicon.png
favicon: https://ws4.sinaimg.cn/large/006tNc79ly1fqd5hpo5g0j3064064mx3.jpg

apple_touch_icon: /images/apple-touch-icon.png
